let num1 = 31;
let num2 = 2;
let multiply = num1 * num2;
console.log(multiply);
let random = Math.floor(Math.random() * Number.MAX_SAFE_INTEGER) + 1;
console.log(random);
let num3 = 64;
let num4 = 8;
let mod = num3 % num4;
console.log(mod);
let numbers = [1, 6, 3, 8, 12, 20, 5];
let max = Math.max(...numbers);
console.log(max);